name: Docker Image CI

on:
  push:
    branches:
      - main # Runs when code is pushed to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest


    steps:
      - name: chekout code
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build Docker Image
        run: docker build -t your-username/devops-website:latest .

      - name: push Docker image to docker hub
        run: docker push rajakokate/website:latest
